#!/usr/bin/env bash

set -e

# Exporting the specific shell we want to work with:

SHELL='/bin/bash'
export SHELL

# Standard dotbot pre-configuration:

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly ARGS="$@"

cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

# Linking dotfiles:

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    --plugin-dir dotbot-brewfile \
    --plugin-dir dotbot-pip \
    -c "$config" $ARGS
}

run_dotbot 'steps/terminal.yml' || true
if [ "$CODESPACES" = true ]; then
  run_dotbot 'steps/codespaces.yml' || true
else
  run_dotbot 'steps/dependencies.yml' || true
fi
run_dotbot 'steps/vscode.yml' || true


# Install my .bashrc

if [ "$CODESPACES" = true ]; then
    # Fix the git_ps1 prompt:
    curl -L https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh > ~/.bash_git
    source ~/.bash_git
    
    # Copy over the .bashrc and script files:    
    cp -R .scripts ~/.scripts
    cp .bashrc ~/.bashrc
    source ~/.bashrc
    
    # Install useful extensions:
    code --install-extension yoshinorin.current-file-path
    code --install-extension sleistner.vscode-fileutils
    code --install-extension peterbe.ghdocs-goer
fi
